# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='', null=True, verbose_name='Name')),
                ('completed', models.BooleanField(choices=[(1, 'Completed'), (0, 'Not Completed')], default=False, verbose_name='Is it finished?')),
                ('text', models.TextField(blank=True, default='', null=True, verbose_name='Task')),
                ('last_update', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Last update')),
            ],
        ),
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='', null=True, verbose_name='Name')),
                ('last_update', models.DateField(default=django.utils.timezone.now, verbose_name='Last update')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='todolist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TODOlist.ToDoList', verbose_name='TODOlist'),
        ),
    ]
